version: '3.8'

services:
  wb_app:
    build: ./wb_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./wb_app/:/usr/src/wb_app/
    ports:
      - 8000:8000
    env_file:
      - ./wb_app/.env
    depends_on:
      - db
  db:
    container_name: wb_db
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=wb
      - POSTGRES_PASSWORD=wb
      - POSTGRES_DB=wb
    expose:
      - 5432
    ports:
      - "5435:5432"

volumes:
  postgres_data: