version: "3.8"

services:
  wb_app:
    restart: always
    build:
      context: ./wb_app
    ports:
      - "8000:8000"
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./:/app

  wb_cards_db:
    container_name: wb_cards_db
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=wb
      - POSTGRES_USER=wb
      - POSTGRES_PASSWORD=wb
    expose:
      - 5432
    ports:
      - "5435:5432"
    networks:
      - wb_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U wb" ]
      interval: 5s
      timeout: 20s
      retries: 100

networks:
  wb_network:

volumes:
  postgres_data: